import "@/app/global.css";
import { UserProvider } from "@/context/UserContext";
export const metadata = {
  title: "Ration Card Management System",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body>{children}</body>
      </UserProvider>
    </html>
  );
}
